/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  safelist: ['text-positive'],
  theme: {
    extend: {
      colors: {
        primary: '#006876',
        'on-primary': '#ffffff',
        'primary-container': '#00acc1',
        'on-primary-container': '#003a42',
        'primary-fixed': '#9eefff',
        'primary-fixed-dim': '#55d7ed',
        'inverse-primary': '#55d7ed',
        secondary: '#636037',
        'on-secondary': '#ffffff',
        'secondary-container': '#e7e1ae',
        'on-secondary-container': '#67643b',
        'secondary-fixed': '#eae4b1',
        'secondary-fixed-dim': '#cdc897',
        tertiary: '#8d4f00',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#da8a36',
        'on-tertiary-container': '#502b00',
        'tertiary-fixed': '#ffdcc0',
        'tertiary-fixed-dim': '#ffb875',
        background: '#f8f9ff',
        'on-background': '#0d1c2f',
        surface: '#f8f9ff',
        'on-surface': '#0d1c2f',
        'surface-variant': '#d5e3fd',
        'on-surface-variant': '#3d494b',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e6eeff',
        'surface-container-high': '#dde9ff',
        'surface-container-highest': '#d5e3fd',
        'surface-bright': '#f8f9ff',
        'surface-dim': '#ccdbf4',
        'surface-tint': '#006876',
        outline: '#6d797c',
        'outline-variant': '#bcc9cc',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'inverse-surface': '#233144',
        'inverse-on-surface': '#ebf1ff',
        positive: '#16a34a',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'stack-gap-sm': '12px',
        'stack-gap-md': '24px',
        'stack-gap-lg': '48px',
        'container-margin-mobile': '20px',
        unit: '8px',
        'max-content-width': '800px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-md':    ['14px', { lineHeight: '1.4', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-md':     ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-lg':     ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-lg':  ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
      maxWidth: {
        content: '800px',
      },
      boxShadow: {
        card:       '0 4px 20px rgba(51, 65, 85, 0.06)',
        'card-hover':'0 8px 30px rgba(51, 65, 85, 0.10)',
      },
    },
  },
  plugins: [],
}
